<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-18T05:26:54Z" name="Default suite" finished-at="2021-01-18T05:27:22Z" duration-ms="27734">
    <groups>
    </groups>
    <test started-at="2021-01-18T05:26:54Z" name="Default test" finished-at="2021-01-18T05:27:22Z" duration-ms="27734">
      <class name="qaEvaluation.FormSubmission">
        <test-method is-config="true" signature="setup()[pri:0, instance:qaEvaluation.FormSubmission@7d0b7e3c]" started-at="2021-01-18T05:26:54Z" name="setup" finished-at="2021-01-18T05:27:08Z" duration-ms="13670" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC3()[pri:0, instance:qaEvaluation.FormSubmission@7d0b7e3c]" started-at="2021-01-18T05:27:08Z" name="TC3" finished-at="2021-01-18T05:27:08Z" duration-ms="105" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.getText()" because "this.fname" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.getText()" because "this.fname" is null
at qaEvaluation.FormSubmission.TC3(FormSubmission.java:103)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC3 -->
        <test-method signature="formTC()[pri:0, instance:qaEvaluation.FormSubmission@7d0b7e3c]" started-at="2021-01-18T05:27:08Z" name="formTC" finished-at="2021-01-18T05:27:15Z" duration-ms="6623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- formTC -->
        <test-method signature="tc2()[pri:0, instance:qaEvaluation.FormSubmission@7d0b7e3c]" started-at="2021-01-18T05:27:15Z" name="tc2" finished-at="2021-01-18T05:27:22Z" duration-ms="7164" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [user] but found [],
expected [user1] but found [],
expected [user1@gmail.com] but found [],
expected [company] but found [],
expected [9898987654] but found [],
expected [12/01/1990] but found [],
expected [QA] but found [],
expected [1000000] but found [],
expected [ASAP] but found [],
expected [mumbai] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [user] but found [],
expected [user1] but found [],
expected [user1@gmail.com] but found [],
expected [company] but found [],
expected [9898987654] but found [],
expected [12/01/1990] but found [],
expected [QA] but found [],
expected [1000000] but found [],
expected [ASAP] but found [],
expected [mumbai] but found []
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at qaEvaluation.FormSubmission.tc2(FormSubmission.java:97)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method is-config="true" signature="close()[pri:0, instance:qaEvaluation.FormSubmission@7d0b7e3c]" started-at="2021-01-18T05:27:22Z" name="close" finished-at="2021-01-18T05:27:22Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- qaEvaluation.FormSubmission -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
